version: '3.8'

services:
  smartdoc-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - STORAGE_TYPE=local
      - PORT=8080
    volumes:
      - .:/app
    command: go run ./cmd/server
    profiles:
      - dev 